---
# Things Homepage can't widget-ize but that I'll want one click away.

- Infrastructure:
    - Tailscale:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com/

- Code:
    - nthncrtr (this repo):
        - abbr: NC
          href: https://github.com/nathancrtr/nthncrtr
    - starmaya:
        - abbr: SM
          href: https://github.com/nathancrtr/starmaya
    - douchi:
        - abbr: DC
          href: https://github.com/nathancrtr/douchi
    - dotfiles:
        - abbr: DF
          href: https://github.com/nathancrtr/.dotfiles
